zookeeper:
 image: confluent/zookeeper
 container_name: zookeeper
 ports:
   - "2181:2181"
   - "15001:15000"
 environment:
 ZK_SERVER_ID: 1
 volumes:
   #- ./host/folder:/container/folder
   - ./logs:/tmp/docker/zk1/logs
   - ./data:/tmp/docker/zk1/data
    
kafka1:
  image: confluent/kafka
  container_name: kafka1
  ports:
    #- "host-port:container-port"
    - "9092:9092"
    - "15002:15000"
  links:
    - zookeeper
  environment:
    - KAFKA_BROKER_ID: 1
    - KAFKA_OFFSETS_STORAGE: kafka
    - # This is Container IP
    - KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 
  volumes:
    #- ./host/folder:/container/folder
    - ./logs:/tmp/docker/kafka1/logs
    - ./data:/tmp/docker/kafka1/data
